-- insert into events(title, description, date_of_publishment,
--                    date_of_event, contact_number,
--                    address, total_stars, review_counter,
--                    start_time, end_time)
-- VALUES ('event', 'event desc', current_timestamp,
--         current_timestamp, 9696,'54.013194, 27.68137', 3, 3,
--         current_timestamp, current_timestamp)